base_link = 'https://brc-hydra.onrender.com'

mensagens = [
    {'id': 0, 'msg': f"Descubra se há dinheiro esperando por você! Faça uma consulta agora em {base_link}!"},
    {'id': 1, 'msg': f"Você já verificou se tem fundos esquecidos? Confira agora em {base_link} e descubra!"},
    {'id': 2, 'msg': f"Pode haver dinheiro que você esqueceu! Consulte seus fundos em {base_link} e descubra!"},
    {'id': 3, 'msg': f"Não deixe seu dinheiro esquecido! Acesse {base_link} e veja se há algo esperando por você!"},
    {'id': 4, 'msg': f"Já pensou que pode ter dinheiro perdido por aí? Faça uma consulta em {base_link} e descubra agora!"},
    {'id': 5, 'msg': f"Há uma chance de dinheiro extra esperando por você! Verifique em {base_link} e não perca essa oportunidade!"},
    {'id': 6, 'msg': f"Dinheiro pode estar onde você menos espera! Consulte em {base_link} e descubra se há algo para você!"},
    {'id': 7, 'msg': f"Faça uma verificação rápida em {base_link} e veja se há dinheiro esquecido em seu nome!"},
    {'id': 8, 'msg': f"Você já conferiu se tem algum dinheiro esquecido? Acesse {base_link} e descubra agora mesmo!"},
    {'id': 9, 'msg': f"Pode haver uma surpresa em sua conta! Consulte {base_link} e descubra se há dinheiro esperando por você!"},
    {'id': 10, 'msg': f"Não perca a chance de descobrir se tem dinheiro esquecido! Faça a consulta em {base_link} agora mesmo!"},
    {'id': 11, 'msg': f"Você sabia que pode ter dinheiro esperando para ser reivindicado? Confira em {base_link} e não deixe passar!"},
    {'id': 12, 'msg': f"Descubra se há algum dinheiro esquecido em seu nome! Acesse {base_link}e faça a consulta agora!"},
    {'id': 13, 'msg': f"Não ignore a possibilidade de ter dinheiro esquecido! Verifique em {base_link} e descubra o que está esperando por você!"},
    {'id': 14, 'msg': f"Já parou para pensar se há dinheiro esquecido em sua conta? Faça a consulta em {base_link} e descubra agora!"},
    {'id': 15, 'msg': f"Há uma maneira fácil de descobrir se tem dinheiro esperando por você! Consulte {base_link} e não perca tempo!"},
    {'id': 16, 'msg': f"Não deixe seu dinheiro esquecido! Acesse {base_link} e descubra se há algum fundo esperando por você!"},
    {'id': 17, 'msg': f"Pode haver uma surpresa em sua conta! Faça uma consulta em {base_link} e descubra se há dinheiro esperando por você!"},
    {'id': 18, 'msg': f"Você já conferiu se tem dinheiro esquecido? Acesse {base_link} e descubra agora mesmo!"},
    {'id': 19, 'msg': f"Descubra se há dinheiro extra em sua conta! Consulte {base_link} e não deixe passar essa oportunidade!"},
    {'id': 20, 'msg': f"Já imaginou se há dinheiro esquecido em seu nome? Acesse {base_link} e descubra agora!"},
    {'id': 21, 'msg': f"Não perca tempo! Consulte {base_link} e descubra se há dinheiro esquecido em sua conta!"},
    {'id': 22, 'msg': f"Você pode estar deixando dinheiro para trás! Faça uma consulta em {base_link} e descubra o que está perdendo!"},
    {'id': 23, 'msg': f"Descubra se há dinheiro esquecido em seu nome! Acesse {base_link} agora e não deixe passar essa oportunidade!"},
    {'id': 24, 'msg': f"Pode haver dinheiro esperando por você! Consulte em {base_link} e descubra se há fundos esquecidos!"},
    {'id': 25, 'msg': f"Não deixe seu dinheiro esquecido! Acesse {base_link} e veja se há algo esperando por você!"},
    {'id': 26, 'msg': f"Há uma chance de dinheiro extra esperando por você! Verifique em {base_link} e não perca essa oportunidade!"},
    {'id': 27, 'msg': f"Dinheiro pode estar onde você menos espera! Consulte em {base_link} e descubra se há algo para você!"},
    {'id': 28, 'msg': f"Faça uma verificação rápida em {base_link} e veja se há dinheiro esquecido em seu nome!"},
    {'id': 29, 'msg': f"Você já conferiu se tem algum dinheiro esquecido? Acesse {base_link} e descubra agora mesmo!"},
    {'id': 30, 'msg': f"Pode haver uma surpresa em sua conta! Consulte {base_link} e descubra se há dinheiro esperando por você!"},
    {'id': 31, 'msg': f"Não perca a chance de descobrir se tem dinheiro esquecido! Faça a consulta em {base_link} agora mesmo!"},
    {'id': 32, 'msg': f"Descubra se há algum dinheiro esquecido em seu nome! Acesse {base_link} agora e faça a consulta!"},
    {'id': 33, 'msg': f"Não ignore a possibilidade de ter dinheiro esquecido! Verifique em {base_link} e descubra o que está esperando por você!"},
    {'id': 34, 'msg': f"Já parou para pensar se há dinheiro esquecido em sua conta? Faça a consulta em {base_link} e descubra agora!"},
    {'id': 35, 'msg': f"Há uma maneira fácil de descobrir se tem dinheiro esperando por você! Consulte {base_link} e não perca tempo!"},
    {'id': 36, 'msg': f"Não deixe seu dinheiro esquecido! Acesse {base_link} e descubra se há algum fundo esperando por você!"},
    {'id': 37, 'msg': f"Pode haver uma surpresa em sua conta! Faça uma consulta em {base_link} e descubra se há dinheiro esperando por você!"},
    {'id': 38, 'msg': f"Você já conferiu se tem dinheiro esquecido? Acesse {base_link} e descubra agora mesmo!"},
    {'id': 39, 'msg': f"Descubra se há dinheiro extra em sua conta! Consulte {base_link} e não deixe passar essa oportunidade!"},
    {'id': 40, 'msg': f"Já imaginou se há dinheiro esquecido em seu nome? Acesse {base_link} e descubra agora!"},
    {'id': 41, 'msg': f"Não perca tempo! Consulte {base_link} e descubra se há dinheiro esquecido em sua conta!"},
    {'id': 42, 'msg': f"Você pode estar deixando dinheiro para trás! Faça uma consulta em {base_link} e descubra o que está perdendo!"},
    {'id': 43, 'msg': f"Descubra se há dinheiro esquecido em seu nome! Acesse {base_link} agora e não deixe passar essa oportunidade!"},
    {'id': 44, 'msg': f"Pode haver dinheiro esperando por você! Consulte em {base_link} e descubra se há fundos esquecidos!"},
    {'id': 45, 'msg': f"Não deixe seu dinheiro esquecido! Acesse {base_link} e veja se há algo esperando por você!"},
    {'id': 46, 'msg': f"Há uma chance de dinheiro extra esperando por você! Verifique em {base_link} e não perca essa oportunidade!"},
    {'id': 47, 'msg': f"Dinheiro pode estar onde você menos espera! Consulte em {base_link} e descubra se há algo para você!"},
    {'id': 48, 'msg': f"Faça uma verificação rápida em {base_link} e veja se há dinheiro esquecido em seu nome!"},
    {'id': 49, 'msg': f"Você já conferiu se tem algum dinheiro esquecido? Acesse {base_link} e descubra agora mesmo!"},
    {'id': 50, 'msg': f"Pode haver uma surpresa em sua conta! Consulte {base_link} e descubra se há dinheiro esperando por você!"}
]